const CONSTANTS = {};
CONSTANTS.ENDPOINT = {};

CONSTANTS.PORT = process.env.PORT || 5000;
CONSTANTS.ENDPOINT.MASTERDETAIL = "/masterdetail";

CONSTANTS.ENDPOINT.GRID = "/grid";
CONSTANTS.ENDPOINT.POSTSESSIONRECORDING = '/sessionrecord';


module.exports = CONSTANTS;
